## Swimming PSB Challenge

> In the challenge you'll be wrangling the the `swimming_psb` data set to produce the output shown at the bottom of this notebook.

> Keep a [Cheatsheet](https://github.com/pandas-dev/pandas/blob/master/doc/cheatsheet/Pandas_Cheat_Sheet.pdf) handy? or the [Pandas API Reference in Docs](https://pandas.pydata.org/pandas-docs/stable/reference/index.html)?

In [1]:
import pandas as pd

psb_df = pd.read_csv('.//data/swimming_psb_data.csv')

psb_df.info()
psb_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16948 entries, 0 to 16947
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   c_Sport        16948 non-null  object
 1   c_Season       16948 non-null  int64 
 2   c_Event        16948 non-null  object
 3   c_Gender       16948 non-null  object
 4   n_DateSort     16948 non-null  int64 
 5   c_Person       16640 non-null  object
 6   c_PersonNatio  16640 non-null  object
 7   c_NOC          16948 non-null  object
 8   c_Result       16948 non-null  object
 9   n_ResultSort   16948 non-null  int64 
 10  c_Class        16948 non-null  object
dtypes: int64(3), object(8)
memory usage: 1.4+ MB


c_Sport  c_Season          c_Event c_Gender  n_DateSort  \
0  Swimming      2018  100m Backstroke      Men    20180809   
1  Swimming      2018  100m Backstroke      Men    20180822   
2  Swimming      2018  100m Backstroke      Men    20180806   
3  Swimming      2018  100m Backstroke      Men    20180819   
4  Swimming      2018  100m Backstroke      Men    20180728   

             c_Person  c_PersonNatio          c_NOC c_Result  n_ResultSort  \
0         Ryan Murphy  United States  United States    51.94         51940   
1            Xu Jiayu          China          China    52.30         52300   
2  Kliment Kolesnikov         Russia         Russia    52.51         52510   
3        Ryosuke Irie          Japan          Japan    52.53         52530   
4        Matt Grevers  United States  United States    52.55         52550   

  c_Class  
0   Elite  
1   Elite  
2   Elite  
3   Elite  
4   Elite

#### 1. Remove ```c_Sport```, ```c_Season``` and ```c_Class``` columns.
> Because you decide you don't need them...

In [12]:
psb_df = psb_df.drop(columns=["c_Season","c_Sport","c_Class"]) 

psb_df

## Drop function? 

KeyError: "['c_Season' 'c_Sport' 'c_Class'] not found in axis"

#### 2. Output all unique events (```c_Event```).
> Becasue you want to checkout which Swimming events are in the data.

In [3]:
## Unique Events

a = psb_df["c_Event"].unique()
a

array(['100m Backstroke', '100m Breaststroke', '100m Butterfly',
       '100m Freestyle', '1500m Freestyle', '200m Backstroke',
       '200m Breaststroke', '200m Butterfly', '200m Freestyle',
       '200m Individual Medley', '4 x 100m Freestyle Relay',
       '4 x 100m Medley Relay', '4 x 200m Freestyle Relay',
       '400m Freestyle', '400m Individual Medley', '50m Backstroke',
       '50m Breaststroke', '50m Butterfly', '50m Freestyle',
       '800m Freestyle'], dtype=object)

#### 3a. Find all rows with NaN values.
> Because you want to identify where these values are coming from...more examples [here](https://datatofish.com/rows-with-nan-pandas-dataframe/).

In [4]:
# Example
# rows_with_nan_values = psb_df[psb_df.isnull().any(axis=1)]
rows_with_nan_values = psb_df[psb_df.isnull().any(axis=1)]

# rows_with_nan_values
rows_with_nan_values

c_Sport  c_Season                   c_Event c_Gender  n_DateSort  \
9743   Swimming      2018  4 x 100m Freestyle Relay      Men    20180809   
9744   Swimming      2018  4 x 100m Freestyle Relay      Men    20180803   
9745   Swimming      2018  4 x 100m Freestyle Relay      Men    20180809   
9746   Swimming      2018  4 x 100m Freestyle Relay      Men    20180809   
9747   Swimming      2018  4 x 100m Freestyle Relay      Men    20180803   
...         ...       ...                       ...      ...         ...   
10046  Swimming      2018  4 x 200m Freestyle Relay    Women    20180824   
10047  Swimming      2018  4 x 200m Freestyle Relay    Women    20180821   
10048  Swimming      2018  4 x 200m Freestyle Relay    Women    20180708   
10049  Swimming      2018  4 x 200m Freestyle Relay    Women    20180708   
10050  Swimming      2018  4 x 200m Freestyle Relay    Women    20180708   

      c_Person c_PersonNatio        c_NOC c_Result  n_ResultSort c_Class  
9743       NaN           NaN       Brazil  3:12.02        192020   Elite  
9744       NaN           NaN       Russia  3:12.23        192230   Elite  
9745       NaN           NaN    Australia  3:12.53        192530   Elite  
9746       NaN           NaN        Japan  3:12.54        192540   Elite  
9747       NaN           NaN        Italy  3:12.90        192900   Elite  
...        ...           ...          ...      ...           ...     ...  
10046      NaN           NaN  New Zealand  8:18.91        498910   Elite  
10047      NaN           NaN    Indonesia  8:21.51        501510   Elite  
10048      NaN           NaN     Portugal  8:24.56        504560   Elite  
10049      NaN           NaN     Slovakia  8:27.47        507470   Elite  
10050      NaN           NaN       Turkey  8:28.37        508370   Elite  

[308 rows x 11 columns]

#### 3b. Find all Unique values in the ```c_Event``` column from the ```rows_with_nan_values``` you created above.
> Because you want to confirm all the NaN values are coming specificly from relay events maybe???

In [5]:
#rows_with_nan_values = psb_df[psb_df.isnull().any(axis=1)]
##df[df['column name'].isnull()]

b = rows_with_nan_values["c_Event"].unique()
b


array(['4 x 100m Freestyle Relay', '4 x 100m Medley Relay',
       '4 x 200m Freestyle Relay'], dtype=object)

#### 4. Drop all rows in `psb_df` with a NaN values. 
> There are several solutions here...you could actually try provide a value for the missing data...however, in this instance, you decide it's ok to just drop all the rows with NaN values.

In [14]:
cleaned_df = psb_df.dropna()
cleaned_df

## How to check if this has successfully dropped Nan rows?

c_Event c_Gender  n_DateSort            c_Person  \
0      100m Backstroke      Men    20180809         Ryan Murphy   
1      100m Backstroke      Men    20180822            Xu Jiayu   
2      100m Backstroke      Men    20180806  Kliment Kolesnikov   
3      100m Backstroke      Men    20180819        Ryosuke Irie   
4      100m Backstroke      Men    20180728        Matt Grevers   
...                ...      ...         ...                 ...   
16943   800m Freestyle    Women    20180726       Klara Bosnjak   
16944   800m Freestyle    Women    20180519     Chantel Jeffrey   
16945   800m Freestyle    Women    20180421          Bindi Ware   
16946   800m Freestyle    Women    20180302    Ebony Blackstone   
16947   800m Freestyle    Women    20180609      Mia Steen Duus   

       c_PersonNatio          c_NOC c_Result  n_ResultSort  
0      United States  United States    51.94         51940  
1              China          China    52.30         52300  
2             Russia         Russia    52.51         52510  
3              Japan          Japan    52.53         52530  
4      United States  United States    52.55         52550  
...              ...            ...      ...           ...  
16943        Croatia        Croatia  9:02.44        542440  
16944         Canada         Canada  9:02.47        542470  
16945      Australia      Australia  9:02.48        542480  
16946      Australia      Australia  9:02.54        542540  
16947        Denmark        Denmark  9:02.55        542550  

[16640 rows x 8 columns]

#### 5. Reset the Index
> Because you've removed some rows, you decide to reset your Dataframe's index (not nessesity in this case, but good practice to do so)

In [15]:
cleaned_df.reset_index(drop=True)

c_Event c_Gender  n_DateSort            c_Person  \
0      100m Backstroke      Men    20180809         Ryan Murphy   
1      100m Backstroke      Men    20180822            Xu Jiayu   
2      100m Backstroke      Men    20180806  Kliment Kolesnikov   
3      100m Backstroke      Men    20180819        Ryosuke Irie   
4      100m Backstroke      Men    20180728        Matt Grevers   
...                ...      ...         ...                 ...   
16635   800m Freestyle    Women    20180726       Klara Bosnjak   
16636   800m Freestyle    Women    20180519     Chantel Jeffrey   
16637   800m Freestyle    Women    20180421          Bindi Ware   
16638   800m Freestyle    Women    20180302    Ebony Blackstone   
16639   800m Freestyle    Women    20180609      Mia Steen Duus   

       c_PersonNatio          c_NOC c_Result  n_ResultSort  
0      United States  United States    51.94         51940  
1              China          China    52.30         52300  
2             Russia         Russia    52.51         52510  
3              Japan          Japan    52.53         52530  
4      United States  United States    52.55         52550  
...              ...            ...      ...           ...  
16635        Croatia        Croatia  9:02.44        542440  
16636         Canada         Canada  9:02.47        542470  
16637      Australia      Australia  9:02.48        542480  
16638      Australia      Australia  9:02.54        542540  
16639        Denmark        Denmark  9:02.55        542550  

[16640 rows x 8 columns]

#### 6. Rename all the column headers in the dataframe, so each header makes sense to you...
> e.g. rename ```c_Person``` to ```athlete```...

In [16]:
cleaned_df.columns = ['Event','Gender','Date Sort','Athlete','Nationality','NOC','Time','Result Sort']
cleaned_df

Event Gender  Date Sort             Athlete    Nationality  \
0      100m Backstroke    Men   20180809         Ryan Murphy  United States   
1      100m Backstroke    Men   20180822            Xu Jiayu          China   
2      100m Backstroke    Men   20180806  Kliment Kolesnikov         Russia   
3      100m Backstroke    Men   20180819        Ryosuke Irie          Japan   
4      100m Backstroke    Men   20180728        Matt Grevers  United States   
...                ...    ...        ...                 ...            ...   
16943   800m Freestyle  Women   20180726       Klara Bosnjak        Croatia   
16944   800m Freestyle  Women   20180519     Chantel Jeffrey         Canada   
16945   800m Freestyle  Women   20180421          Bindi Ware      Australia   
16946   800m Freestyle  Women   20180302    Ebony Blackstone      Australia   
16947   800m Freestyle  Women   20180609      Mia Steen Duus        Denmark   

                 NOC     Time  Result Sort  
0      United States    51.94        51940  
1              China    52.30        52300  
2             Russia    52.51        52510  
3              Japan    52.53        52530  
4      United States    52.55        52550  
...              ...      ...          ...  
16943        Croatia  9:02.44       542440  
16944         Canada  9:02.47       542470  
16945      Australia  9:02.48       542480  
16946      Australia  9:02.54       542540  
16947        Denmark  9:02.55       542550  

[16640 rows x 8 columns]

#### 7. Transform each value in the ```date_sort``` column into a DateTime Object using the [```.to_datetime```](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_datetime.html) method.
> Because it's better to handle dates as actual DateTime objects in Python...

In [53]:
## data_table['Date Time'] = pandas.to_datetime(data_table['Date'], format='%d %b %y')

#cleaned_df['Date Sort'] = pd.to_datetime(cleaned_df['Date Sort'], format='%y%m%d')

## Error

#### 8. Create a column for each athlete's ```first name``` and ```last name```.
> Seems futile, but you decide this may save you ALOT of time in the future...

In [33]:
new = cleaned_df["Athlete"].str.split(" ", n = 1, expand = True)
cleaned_df["First Name"]= new[0]
cleaned_df["Last Name"]= new[1] 
new

## Have I done this correctly??

/shared-libs/python3.7/py-core/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/shared-libs/python3.7/py-core/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


0           1
0         Ryan      Murphy
1           Xu       Jiayu
2      Kliment  Kolesnikov
3      Ryosuke        Irie
4         Matt     Grevers
...        ...         ...
16943    Klara     Bosnjak
16944  Chantel     Jeffrey
16945    Bindi        Ware
16946    Ebony  Blackstone
16947      Mia  Steen Duus

[16640 rows x 2 columns]

#### Finale: Have a final Dataframe that contains only the top (up to 4) Great British swimmers for each event and gender. Then save this data into a new csv or json file.
> Hint: The dataset you have been handling is already sorted and grouped. Fastest swimmers (top four) would be at the top of each group (gender/event).

In [50]:
## Sort for GB Athletes only
cleaned_df.sort_values(['Result Sort'])
NOC = cleaned_df['NOC']
df = cleaned_df.drop(cleaned_df[cleaned_df.NOC != 'Great Britain'].index)
df

## Top 4 per event

df2 = df.groupby(['Gender','Event']).head(4)
df2

## Save data into new csv
df2.to_csv('data/swimming_psb_data2.csv')



### Bonus

**The aim is to create a visualisation** that shows the performance standards for each gender and event relative to the respective world record at the time. This visualisation uses world record times (2018) found in the `world_records_swimming.json` file (`data` folder). To enable a visualisation that can show both genders and all the events, at once, requires us to standardise the results data. We can do this by creating another ***result*** that is the relevent world record as a percentage of the actual result e.g.


> **Men 100m Backstroke - Ryan Murphy, United States - `51.94` (seconds) or `51940` (milliseconds)**


In [51]:
import json

wrs = json.load(open('data/world_records_swimming.json'))

wr_secs = float(wrs['Men']['100m Backstroke'])
result = 51.94

wr_percentage = wr_secs / result * 100

round(wr_percentage, 2)


99.83

> Hints

1. Include any relevant cleaning steps in the cell below before attempting to create the new column with the percentage data.
2. Note that some of the world record times are not in seconds. It may be an idea to reformat the world records into milliseconds?
3. We import [```seaborn```](https://seaborn.pydata.org/generated/seaborn.violinplot.html) to create the Violin Plots. e.g. https://seaborn.pydata.org/generated/seaborn.violinplot.html

In [68]:
import json
import pandas as pd
import seaborn as sns

wrs = json.load(open('data/world_records_swimming.json'))  # Pandas is not always nessisary when handling data, a simple dictionary can be far simpler to handle ;)
print (wrs)

## Reformat WR into milliseconds


psb_viz_df = pd.read_csv('data/swimming_psb_data.csv')
psb_viz_df = psb_viz_df.drop(columns=["c_Season","c_Sport","c_Class","n_DateSort","c_Person","c_PersonNatio","c_NOC"]) 
psb_viz_df
#psb_viz_df['newColumn'] = psb_viz_df['c_Result'].dt.total_seconds()

#ax = sns.violinplot(x="Event", y="percent_of_wr", hue="Gender",data=psb_viz_df, palette="muted")


{'Men': {'50m Freestyle': '20.91', '100m Freestyle': '46.91', '200m Freestyle': '1:42.00', '400m Freestyle': '3:40.07', '800m Freestyle': '7:32.12', '1500m Freestyle': '14:31.02', '50m Backstroke': '24.00', '100m Backstroke': '51.85', '200m Backstroke': '1:51.92', '50m Breaststroke': '25.95', '100m Breaststroke': '57.00', '200m Breaststroke': '2:06.67', '50m Butterfly': '22.27', '100m Butterfly': '49.82', '200m Butterfly': '1:51.51', '200m Individual Medley': '1:54.00', '400m Individual Medley': '4:03.84'}, 'Women': {'50m Freestyle': '23.67', '100m Freestyle': '51.71', '200m Freestyle': '1:52.98', '400m Freestyle': '3:56.46', '800m Freestyle': '8:04.79', '1500m Freestyle': '15:20.48', '50m Backstroke': '26.98', '100m Backstroke': '58.00', '200m Backstroke': '2:04.06', '50m Breaststroke': '29.4', '100m Breaststroke': '1:04.13', '200m Breaststroke': '2:19.11', '50m Butterfly': '24.43', '100m Butterfly': '55.48', '200m Butterfly': '2:01.81', '200m Individual Medley': '2:06.12', '400m Indi

c_Event c_Gender c_Result  n_ResultSort
0      100m Backstroke      Men    51.94         51940
1      100m Backstroke      Men    52.30         52300
2      100m Backstroke      Men    52.51         52510
3      100m Backstroke      Men    52.53         52530
4      100m Backstroke      Men    52.55         52550
...                ...      ...      ...           ...
16943   800m Freestyle    Women  9:02.44        542440
16944   800m Freestyle    Women  9:02.47        542470
16945   800m Freestyle    Women  9:02.48        542480
16946   800m Freestyle    Women  9:02.54        542540
16947   800m Freestyle    Women  9:02.55        542550

[16948 rows x 4 columns]

##### Reference Image
![BonusViz](./data/swimming_challenge.png)

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=c64a6c44-3e0c-4ffa-ba8f-f8e94894d929' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>